### ISSUE TITLE
Add basic media controller

### ISSUE THREAD

**Issue by sumnerboy12** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#10]
Might need to be a double width tile (like the blind control).

Ideally would have 3 lines of text for track, artist, album and then a set of icons for PLAY, PAUSE. PREV, NEXT.

We could add volume control as well, or make that another tile type you setup in conjunction with the media tile if you wish.

**Comment by moinmoin-sh** [comment]
Functions that require more than one tile space became more complicated with the "any tile every where" concept. It's tricky to configure that correctly to make sure the expected space is allocated and reserved.
My idea to solve this is to open an overlay screen with a special tile/combination of buttons / controls specific to the type of the initial tile. This would be valid for Blinds, Color Picker, KeyPad, MediaPlayer , ... 
This concept gives us more room for the special controls, hides control elements that are not need to be visible and prevents from unintended touch.

**Comment by moinmoin-sh** [comment]
Here is a proposal for a Mini Player following 100% our tile concept and made from 5 of our existing tiles types and 1 modified - alternating state depending icon  and left/right arrows for previous and next track.

https://user-images.githubusercontent.com/53935853/170367191-4d4a0861-a981-4296-b907-ad9268251991.mp4

**Comment by sumnerboy12** [comment]
Yeah I like the look of that! The mini player tile looks fantastic - exactly what I was envisaging. And clever use of the text tiles for media info.

**Comment by plains203** [comment]
I like the mini player tile. One small request with that though is, can we implement a double tap action on that which could be used for another command such as for stop?

**Comment by moinmoin-sh** [comment]
`Double click` is not supported, but `long press` is. That's what I had in mind regarding `STOP` command ,
So : 
- single click toggles between` play / pause `-> sends stat/  ` {"screen":1, "tile":1, "type":"button", "event":"single" , "state":"on"}`
- long press `stop`                                        -> sends stat/  `{"screen":1, "tile":1, "type":"button", "event":"hold" , "state":"on"}`
That should confirm with our messaging standard.
State switching (on / off) is users (NR) resposibility (Panel FW will send stat/ only, no internal state change)

**Comment by plains203** [comment]
That sounds good. Will the long press be implemented on other tiles as well then? I can see it being useful and assume it would be similar work to add it for global tiles vs one type.

**Comment by moinmoin-sh** [comment]
I planed to use the long press for internal purpose, but didn't find a use case until now. I can make the long press availble easily as a standard for all tiles. I'll enable it in the next version and we can check how it feels.
