### ISSUE TITLE
The event message in MQTT and the serial logger mismatch the numbers

### ISSUE THREAD

**Issue by plains203** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#13]
When you tap a button on the screen the screen and tile number reported via MQTT and via the Serial Screen are different. The serial output is incorrect and needs to be incremented by 1 as it starts at 0. 

![image](https://user-images.githubusercontent.com/11266144/166879424-8e345b36-c47a-4354-a335-9e191594a922.png)

**Comment by moinmoin-sh** [comment]
That's on purpose. Debug outputs are zero-based (as in code) , messaging is one-based (for user) .
Anyway, these outputs are not "official" and change rapidly. It's just for me and my testing.
