### ISSUE TITLE
Seeing intermittent resending of tile events

### ISSUE THREAD

**Issue by sumnerboy12** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#2]
I have seen it twice now, when the panel starts sending repeated tile events. Usually every minute or so. 

I am constantly sending commands from NodeRED to update the sub label with timer information.

Wondering if it might be related to that.

I have checked and am pretty certain I don't have any NodeRED flows sending stat/ messages so it must be coming from the panel.

**Comment by moinmoin-sh** [comment]
Hard to diagnose. Can you cresate/define a scenario  / use case / simplified NR-flow / ... which make it reproducable to trouble shoot and verify ?

**Comment by sumnerboy12** [comment]
Yeah very difficult to diagnose - wanted to just get it recorded here - not expecting you to dive in yet. Once I see the code I will have a dig around and see if I can see anything that might be causing it. I am not even certain it is your firmware, but that is the likely culprit at this point.

**Comment by sumnerboy12** [comment]
Haven't seen this for a few days now - I wonder if it was something on the screen causing false positives.
