### ISSUE TITLE
Can we support swipe gestures? E.g. swipe left to go back a screen?

### ISSUE THREAD

**Issue by sumnerboy12** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#3]

**Comment by moinmoin-sh** [comment]
Yes we can - I think.
How to you want to navigate ?
- thru all screens by inc/dec screen number
- called screen stack , like back button

**Comment by sumnerboy12** [comment]
Yeah good question - I think all screens by inc/dec screen number sounds good. It would mean you don't need any dedicated tiles for navigation potentially.

**Comment by moinmoin-sh** [comment]
I pushed an experimental version. 
Swipe is not properly detected by my panel. Please check how it works for you.

**Comment by sumnerboy12** [comment]
It works if I swipe on a part of the screen with no active tiles (i.e. tiles which generate an event). So swiping from either an empty tile or readonly tile works, but any active tile results in that tile sending an event and no swipe action occurs.

**Comment by moinmoin-sh** [comment]
There is a new version DEV-0.1.7 available. It' not posible to use a screen fully populated with touch sensitive tiles with the swipe gesture as it is implemented in lvgl. As a possible solution I enabled the footer ares only to be swipe sensitive.

**Comment by sumnerboy12** [comment]
Swiping in the footer works well - much easier than trying to hit the Home/Back button.

Can you hide screens with nothing on them? Otherwise it is unclear if the swipe didn't work, or I am swiping thru multiple blank screens ;).

The `"colour:[]` change is almost working - only thing is when the tile is `off` it is showing the icon as green, but the other tiles default to white when `off`, and only green when `on`.

**Comment by moinmoin-sh** [comment]
`"color": [] ` is part of the `{"setstate":[{"screen":S, "tile":N, "state":"STATE", "sublabel":"ANY", "color":[R,G,B]}]}'` cmnd. When no state is provided together with color, the actual state of the icon is taken for what the color is changed.

Instaed of hiding empty screens I would prefer to create a default screen label like `Screen 4` .

**Comment by moinmoin-sh** [comment]
I suggest that I remove the `back `buton from the footer and leave it to be the `Home `button (allways visible). I also remove the small dots.
Navigation : 
- tiles with a link -> jump to linked screen
- Home button -> jumps to HomeScreen
- Settings button -> jumps to SettingsScreen
- swipe in footer -> inc/dec screen number

**Comment by sumnerboy12** [comment]
> `"color": [] ` is part of the `{"setstate":[{"screen":S, "tile":N, "state":"STATE", "sublabel":"ANY", "color":[R,G,B]}]}'` cmnd. When no state is provided together with color, the actual state of the icon is taken for what the color is changed.
> 
> Instaed of hiding empty screens I would prefer to create a default screen label like `Screen 4` .
> 

Not sure I follow. How do I reset the icon to the default color when off, i.e. white on black?

Currently it is green on black after I have manually set the color and then reset it to [], with state off.

**Comment by moinmoin-sh** [comment]
OK,I got it. I didn't expect that you changed the OFF color. I propose to reset both (ON-color and OFF-color) to the defaults when a color of [] is received , independent of the actual state.

**Comment by sumnerboy12** [comment]
I have a generic flow which sends a `cmnd/` message whenever the device changes state. And in that flow if I am not setting an explicit colour I just send an empty `{ "color":[] }`. Hope that makes sense.

**Comment by moinmoin-sh** [comment]
OK,that makes sense. I'll make the changes to supoort that.

**Comment by moinmoin-sh** [comment]
done with DEV-0.1.9
