### ISSUE TITLE
Add an icon/type for LED lights

### ISSUE THREAD

**Issue by sumnerboy12** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#30]
Would be good to have a few different light icons to pick from, for when there are multiple lights on a screen you want to differentiate.

**Comment by sumnerboy12** [comment]
![image](https://user-images.githubusercontent.com/5060842/173443391-3675ec31-19fa-41ce-82b5-c2fb8cc2edc4.png)

**Comment by sumnerboy12** [comment]
Having a large set of icons will be very useful I think - but I am not sure the best way to structure things. I still wonder if we are better off having a `tileType` and `tileIcon` as separate config - where type is one of `button`, `level`, `readonly`, `number`, `text` `dropdown` etc?

Rather than coupling the tile function to the icon.

**Comment by plains203** [comment]
> Having a large set of icons will be very useful I think - but I am not sure the best way to structure things. I still wonder if we are better off having a `tileType` and `tileIcon` as separate config - where type is one of `button`, `level`, `readonly`, `number`, `text` `dropdown` etc?
> 
> Rather than coupling the tile function to the icon.

I think this would be ideal also, particularly as the usage and adoption grows. Being able to use more icons will be helpful. Not sure how that affects memory usage though. I would like a desk fan icon for instance as I don't have a ceiling fan. The different light icons also makes sense to me. 

Where are these icons coming from at the moment?

**Comment by moinmoin-sh** [comment]
> Having a large set of icons will be very useful I think - but I am not sure the best way to structure things. I still wonder if we are better off having a `tileType` and `tileIcon` as separate config - where type is one of `button`, `level`, `readonly`, `number`, `text` `dropdown` etc?
> 
> Rather than coupling the tile function to the icon.

I totaly agree. I've started to think about this and will work on that after the key pad integration is finished. That will be a breaking change and I won't add further icons and functions before the restructure is done. I'll share my thoughts as a base for further discussion.

> Where are these icons coming from at the moment?

Icons are from here [icons8](https://icons8.de/ ). The style is  iOS / outline

**Comment by moinmoin-sh** [comment]
I think this can be closed since we have the custom icons in place.
