### ISSUE TITLE
Clicking a `button_level_down` tile doesn't generate a button/single event

### ISSUE THREAD

**Issue by sumnerboy12** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#39]
v0.2.0

This appears to work for `button_level_up` tiles, but not `_down` (blind) tiles.

**Comment by moinmoin-sh** [comment]
I fixed the bug. Do you want a new release or are you going with the newer version (image display) anyway?

Or can we bugfix the current release (0.2.0) backwards without  creating a new one?
