### ISSUE TITLE
Can we add Switch as a Button type

### ISSUE THREAD

**Issue by plains203** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#8]
I would like if we had a generic power icon as a button type. I could use that for various relays and the like.

**Comment by moinmoin-sh** [comment]
That's a good idea for an additional type (icon) which may be used in many cases.
It'll make it into one of the next vesions.

**Comment by plains203** [comment]
Thanks

**Comment by plains203** [comment]
That looks good thanks
