### ISSUE TITLE
The screen stays black when it receives a message

### ISSUE THREAD

**Issue by plains203** [moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW#9]
Sending a message to the screen while the backlight is off possibly should wake the screen to x Brightness so the message displays instead of a manual requirement to wake the screen up. Alternatively it would be useful to report the screen brightness when that is changed so that you could handle that in a flow and would also be useful in other cases.

**Comment by moinmoin-sh** [comment]
Turning on the brightness when a setstate `cmnd/` is received may not be wanted for every one. That should be left to the HomeAutomation to decide if the brightness should change.
Reporting back the actual brightness will be included in the` tele/ `event which will be added to one upcoming version.

**Comment by plains203** [comment]
Yeah if the brightness is part of tele messages that will be ideal & solve this issue (and some others) nicely.

**Comment by plains203** [comment]
The new telemetry function is nice. 
I will be able to use that in my flow thanks.
